module.exports = {
  ingredients: [
    "monkfish",
    "swordfish",
    "garlic powder",
    "tomato paste",
    "habanero chilies",
    "catfish",
    "huckleberries",
    "sausages",
    "blackberries",
    "cauliflower",
    "asparagus",
    "jelly beans",
    "green beans",
    "oregano",
    "guavas",
    "halibut",
    "curry powder",
    "peanuts",
    "cactus",
    "feta cheese",
    "red beans",
    "Cappuccino Latte",
    "mascarpone",
    "dumpling",
    "kale",
    "limes",
    "lettuce",
    "salmon",
    "passion fruit",
    "broccoli",
    "okra",
    "cod",
    "creme fraiche",
    "sour cream",
    "black olives",
    "oatmeal",
    "onion powder",
    "panko bread crumbs",
    "paprika",
    "dates",
    "pheasants",
    "portabella mushrooms",
    "vinegar",
    "chai",
    "Romano cheese",
    "cilantro",
    "bacon grease",
    "olive oil",
    "bean sprouts",
    "bagels",
  ],
  menuItems: [
    'Saffron and harissa yoghurt',
    'Borscht and caraway salad',
    'Jalapeno and savoy cabbage salad',
    'Gochu jang and sprout salad',
    'Morel and cavatelli salad',
    'Kiwi fruit and nasturtium salad',
    'Haricot and currant salad',
    'Parma ham and loquat salad',
    'Radish and bacon salad',
    'Soya margarine and bulgur wheat salad', 
    'Roast daikon',
    'Kiwano and tofu',
    'Chicory and fontina cheese',
    'Chilli and chinese cabbage',
    'Banana and elderberry',
    'Honeyberry and jaggery',
    'Tomato and truffle',
    'Beetroot and potato', 
    'Pineapple and harissa salad',
    'Thai basil and bouquet garni salad'
  ],
  menuDescription: [
    'A light yoghurt made with saffron and harissa',
    'Borscht and fresh caraway served on a bed of lettuce',
    'A crisp salad featuring fresh jalapeno and savoy cabbage',
    'A crunchy salad featuring gochu jang and fresh sprout',
    'A crisp salad featuring morel and cavatelli',
    'Fresh kiwi fruit and nasturtium served on a bed of lettuce',
    'A crisp salad featuring dried haricot and fresh currant',
    'Parma ham and fresh loquat served on a bed of lettuce',
    'A crunchy salad featuring fresh radish and thick bacon',
    'A crunchy salad featuring soya margarine and bulgur wheat',
    'Roast daikon with all the trimmings',
    'Basmalti rice and fresh daikon served on a bed of lettuce',
    'Edam and fresh feijoa served on a bed of lettuce',
    'A crisp salad featuring jaggery and fresh borlotti bean',
    'A crisp salad featuring olive and dried coriander',
    'Beef tomatoes and peppermint served on a bed of lettuce',
    'Ricotta and fresh pomegranate served on a bed of lettuce',
    'Fresh quinoa and nutmeg served on a bed of lettuce',
    'Black cardamom and licorice served on a bed of lettuce'
  ]
}